version: '3.7'

services:
  db:
    build: ./postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_MULTIPLE_DATABASES: >-
        commuting
